apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: automationbrokers.automationbroker.io
spec:
  group: automationbroker.io
  names:
    kind: AutomationBroker
    listKind: AutomationBrokerList
    plural: automationbrokers
    singular: automationbroker
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
